server:
  port: 9999
  
zuul:
  ignored-services: '*'
  ignoredPatterns: /**/api/**
  routes:
    user-service: /user/** 
    customer-data-service: /customer-data/**
    
security:
  oauth2:
    resource:
      userInfoUri: http://localhost:8002/uaa/user
  ignored: /manage/**
    
eureka:
  instance:
    prefer-ip-address: true
    statusPageUrlPath: /manage/info
    healthCheckUrlPath: /manage/health
    metadata-map:
      management.context-path: ${management.context-path}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
management:
  context-path: /manage