server:
  port: 9999
zuul:
  ignored-services: '*'
  ignoredPatterns: /**/api/**
  routes:
    user-service: /user/** 
security:
  oauth2:
    resource:
      userInfoUri: http://localhost:8002/uaa/user
  ignored: /info, /health
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/