server:
  port: 8002
  contextPath: /uaa
security:
  user:
    password: password
  enable-csrf: false
eureka:
  instance:
    prefer-ip-address: true
    non-secure-port: 8002
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  jpa:
    database: H2
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    initialize: true