server:
  port: 8000
  
logging:
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'
    
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sanderino666/spring-cloud-stuff-config.git
          
eureka:
  instance:
    prefer-ip-address: true
    statusPageUrlPath: /manage/info
    healthCheckUrlPath: /manage/health
    metadata-map:
      management.context-path: ${management.context-path}
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
management:
  context-path: /manage